import type { Story } from './types';

export const mockStoryData: Story = {
  id: 4,
  title: "El Conjunto Embrujado de Chía",
  summary: "Un guardia de seguridad relata la intensa actividad paranormal en un conjunto de apartamentos en Chía: sombras en las cámaras, ascensores que se mueven solos, luces que se prenden, y cómo lo han jalado físicamente de la silla.",
  fullText: "La noche era especialmente fría en Chía cuando Yonjairo se acomodó frente a los monitores de seguridad. Como todas las noches desde hacía un año, sabía que su turno sería cualquier cosa menos tranquilo. El conjunto residencial de tres torres, con sus 120 apartamentos modernos, escondía un secreto que ningún arquitecto había considerado durante la construcción: estaba edificado sobre un antiguo cementerio indígena...",
  imageUrl: "https://i.postimg.cc/T3WrMwmy/image.png",
  backgroundImageUrl: "https://i.postimg.cc/GmxWFcV5/image-1.png",
  imageHint: "haunted apartment",
  location: "Chía, Cundinamarca",
  impact: 4,
  credibility: 3,
  duration: 25,
  tags: ["Poltergeist", "Apartamentos", "Guacas"],
  isBasedOnRealTestimony: true,
  audioUrl: "/audio/mock-story.mp3",
  witnesses: [
    { name: "Yonjairo", role: "Vigilante" },
    { name: "15 residentes", role: "" }
  ],
  eventDate: "Diciembre 2023 - Presente",
  relatedStories: [1, 2, 3, 5],
};

export const mockStories: Story[] = [
  mockStoryData,
  {
    id: 1,
    title: "La Llorona del Río Fucha",
    imageUrl: "https://i.postimg.cc/MZY33sdn/image-5.png",
    imageHint: "crying ghost",
    location: "Bogotá, Cundinamarca",
    impact: 5,
    duration: 15,
    tags: ["Fantasmas/Apariciones", "Leyendas"],
    credibility: 5,
    isBasedOnRealTestimony: true,
    summary: "El lamento de una mujer se escucha en las orillas del río, buscando a sus hijos perdidos.",
    audioUrl: "/audio/mock-story.mp3",
    fullText: "Cuentan los más viejos del barrio que cuando la niebla baja y cubre el río Fucha, un lamento helado se abre paso entre el murmullo del agua. Es la Llorona, condenada a buscar eternamente a los hijos que ahogó en un arrebato de locura.",
    witnesses: [{ name: "Ancianos del barrio", role: "" }],
    eventDate: "Desde 1950",
    relatedStories: [2, 4],
  },
  {
    id: 2,
    title: "El Fantasma de la Candelaria",
    imageUrl: "https://i.postimg.cc/G2t90gvb/image-8.png",
    imageHint: "colonial ghost",
    location: "Bogotá, Cundinamarca",
    impact: 3,
    duration: 10,
    tags: ["Fantasmas/Apariciones", "Casas Antiguas"],
    credibility: 4,
    isBasedOnRealTestimony: true,
    summary: "Un monje sin cabeza deambula por las calles empedradas del centro histórico de Bogotá.",
    audioUrl: "/audio/mock-story.mp3",
    fullText: "En el corazón de Bogotá, donde las casonas coloniales guardan secretos centenarios, se aparece la figura de un monje. Camina sin prisa, su hábito oscuro meciéndose en el viento, pero al acercarse, los trasnochadores descubren con horror que no tiene cabeza.",
    witnesses: [{ name: "Estudiantes universitarios", role: "" }],
    eventDate: "Noches de luna llena",
    relatedStories: [1, 3],
  },
  {
    id: 3,
    title: "La Casa de los Lamentos",
    imageUrl: "https://i.postimg.cc/KvR77QVS/image-6.png",
    imageHint: "haunted house",
    location: "Medellín, Antioquia",
    impact: 4,
    duration: 30,
    tags: ["Poltergeist", "Casas Antiguas"],
    credibility: 3,
    isBasedOnRealTestimony: true,
    summary: "Una familia es atormentada por fenómenos violentos en su nueva casa.",
    audioUrl: "/audio/mock-story.mp3",
    fullText: "La familia Pérez creyó haber encontrado la casa de sus sueños en un barrio tranquilo de Medellín. Pero pronto, los susurros se convirtieron en gritos, las puertas se cerraban de golpe y los objetos volaban por los aires, lanzados por una fuerza invisible y malévola.",
    witnesses: [{ name: "Familia Pérez", role: "" }],
    eventDate: "2019",
    relatedStories: [4, 5],
  },
    {
    id: 5,
    title: "El Demonio de Monserrate",
    imageUrl: "https://i.postimg.cc/BQLZB1Bw/image-4.png",
    imageHint: "mountain demon",
    location: "Bogotá, Cundinamarca",
    impact: 5,
    duration: 22,
    tags: ["Posesiones y Demonios", "Lugares Sagrados"],
    credibility: 2,
    isBasedOnRealTestimony: false,
    summary: "Una antigua leyenda sobre un demonio que habita en las cuevas del cerro de Monserrate.",
    audioUrl: "/audio/mock-story.mp3",
    fullText: "Se dice que en las entrañas del cerro tutelar de Bogotá, más allá de la basílica, habita una entidad oscura. Atrae a los peregrinos desprevenidos con promesas de tesoros y los somete a su voluntad. Pocos han visto su verdadera forma y han vuelto para contarlo.",
    witnesses: [{ name: "Leyenda popular", role: "" }],
    eventDate: "Siglo XVII",
    relatedStories: [1, 2, 4],
  },
];
